// Inline SQL suggestions, generated by whatever model the user has installed in
// Ollama.
//
// The rule the whole service is built around: a suggestion is an offer. Every
// way this can go wrong — Ollama not installed, no models, a schema that will
// not load, a model that answered with prose — ends as `completion: null` and a
// log line. Nothing here is ever a user facing error, because the user is in the
// middle of typing.
import { Effect, Option } from 'effect'

import type {
  CompletionRequest,
  CompletionResponse,
  CompletionStatusResponse,
  DatabaseType,
  SchemaInfoDto
} from '@/glue/api/schemas'
import { completionMessages } from '@/glue/completions'
import { buildCompletionPrompt } from '@/main/ai/completion-prompt'
import { normalizeCompletion } from '@/main/ai/completion-text'
import { AdapterFactory } from './adapter-factory'
import { AppSettings } from './app-settings'
import { DatabaseService } from './database-service'
import { Ollama } from './ollama'

// Coding models first, in the order they are worth reaching for. Matched as a
// prefix so a tag (`qwen2.5-coder:7b`) counts.
const modelPreference = [
  'qwen2.5-coder',
  'qwen3-coder',
  'deepseek-coder',
  'codellama',
  'codegemma',
  'starcoder2'
]

// Asking Ollama what it has takes a round trip, so the answer is held between
// keystrokes. Short when it was not there — someone who just started it should
// not have to wait five minutes — and long when it was.
const availableTtl = 5 * 60 * 1000
const unavailableTtl = 30 * 1000

// Introspecting the user's database is a real query against a real connection;
// doing it per keystroke pause would be worse than the inference. Bounded in
// both directions per the memory rules: entries expire, and the map never holds
// more than a handful of connections' worth.
const schemaTtl = 5 * 60 * 1000
const maxCachedSchemas = 4

interface Availability {
  checkedAt: number
  models: string[]
  reachable: boolean
}

interface CachedSchema {
  databaseType: DatabaseType
  loadedAt: number
  schema: SchemaInfoDto
}

interface ModelChoice {
  selectedModel: string | null
  storedModelMissing: boolean
}

// Exported for its own test: which model gets used is the decision most likely
// to surprise someone, and it depends only on these two lists.
export function selectModel(
  installedModels: string[],
  storedModel: string | null
): ModelChoice {
  if (storedModel !== null && installedModels.includes(storedModel)) {
    return { selectedModel: storedModel, storedModelMissing: false }
  }

  const storedModelMissing = storedModel !== null

  for (const preference of modelPreference) {
    const match = installedModels.find((model) => model.startsWith(preference))

    if (match !== undefined) {
      return { selectedModel: match, storedModelMissing }
    }
  }

  return { selectedModel: installedModels[0] ?? null, storedModelMissing }
}

export class Completions extends Effect.Service<Completions>()('Completions', {
  accessors: true,
  dependencies: [
    AdapterFactory.Default,
    AppSettings.Default,
    DatabaseService.Default,
    Ollama.Default
  ],
  effect: Effect.gen(function* () {
    const adapterFactory = yield* AdapterFactory
    const appSettings = yield* AppSettings
    const databases = yield* DatabaseService
    const ollama = yield* Ollama

    // Both caches live in this closure rather than at module scope, so they are
    // owned by the service and released with it.
    let availability: Availability | null = null

    const schemas = new Map<string, CachedSchema>()

    const checkAvailability = Effect.gen(function* () {
      const models = yield* ollama.listModels.pipe(
        Effect.catchAll((error) =>
          Effect.logDebug(
            `Ollama is not answering at ${ollama.host}: ${error.message}`
          ).pipe(Effect.as(null))
        )
      )

      const checked: Availability = {
        checkedAt: Date.now(),
        models: models ?? [],
        reachable: models !== null
      }

      availability = checked

      return checked
    })

    const cachedAvailability = Effect.suspend(() => {
      if (availability === null) {
        return checkAvailability
      }

      const ttl = availability.reachable ? availableTtl : unavailableTtl

      if (Date.now() - availability.checkedAt > ttl) {
        return checkAvailability
      }

      return Effect.succeed(availability)
    })

    const loadSchema = (databaseId: string) =>
      Effect.gen(function* () {
        const cached = schemas.get(databaseId)

        if (cached !== undefined && Date.now() - cached.loadedAt <= schemaTtl) {
          return cached
        }

        const record = yield* databases.getWithSecrets(databaseId)

        if (Option.isNone(record)) {
          return null
        }

        const adapter = adapterFactory.create(record.value.connection)

        const schema = yield* Effect.tryPromise(() => adapter.getSchema())

        const loaded: CachedSchema = {
          databaseType: record.value.connection.type,
          loadedAt: Date.now(),
          schema
        }

        // Re-inserting moves the key to the end, so the first key is always the
        // least recently loaded one.
        schemas.delete(databaseId)
        schemas.set(databaseId, loaded)

        if (schemas.size > maxCachedSchemas) {
          const oldest = schemas.keys().next()

          if (!oldest.done) {
            schemas.delete(oldest.value)
          }
        }

        return loaded
      }).pipe(
        // A schema that will not load is not worth failing over: the model can
        // still continue the statement, it just has no column names to use.
        Effect.catchAll((error) =>
          Effect.logWarning(
            `Could not load the schema for suggestions: ${error.message}`
          ).pipe(Effect.as(null))
        )
      )

    const messageFor = (
      choice: ModelChoice,
      enabled: boolean,
      reachable: boolean
    ): string => {
      if (!reachable) {
        return completionMessages.unreachable(ollama.host)
      }

      if (choice.selectedModel === null) {
        return completionMessages.noModels
      }

      // Said even when a fallback was found: the user picked a model and it is
      // not the one running.
      if (choice.storedModelMissing) {
        return completionMessages.modelMissing(choice.selectedModel)
      }

      if (!enabled) {
        return completionMessages.disabled(choice.selectedModel)
      }

      return completionMessages.using(choice.selectedModel)
    }

    // Always asks Ollama rather than trusting the cache: this runs when the
    // user opens Settings, which is exactly when they have just installed
    // something and want to see it.
    const status = Effect.fn('Completions.status')(function* () {
      const settings = yield* appSettings.read()
      const checked = yield* checkAvailability

      const choice = selectModel(checked.models, settings.aiCompletionModel)

      const response: CompletionStatusResponse = {
        available: checked.reachable && choice.selectedModel !== null,
        enabled: settings.aiCompletionsEnabled,
        message: messageFor(
          choice,
          settings.aiCompletionsEnabled,
          checked.reachable
        ),
        models: checked.models,
        selectedModel: choice.selectedModel
      }

      return response
    })

    const complete = Effect.fn('Completions.complete')(
      function* ({ databaseId, prefix, suffix }: CompletionRequest) {
        const nothing: CompletionResponse = { completion: null }

        if (prefix.trim().length === 0) {
          return nothing
        }

        const settings = yield* appSettings.read()

        if (!settings.aiCompletionsEnabled) {
          return nothing
        }

        const checked = yield* cachedAvailability

        if (!checked.reachable) {
          return nothing
        }

        const { selectedModel } = selectModel(
          checked.models,
          settings.aiCompletionModel
        )

        if (selectedModel === null) {
          return nothing
        }

        const context =
          databaseId === undefined ? null : yield* loadSchema(databaseId)

        const prompt = buildCompletionPrompt({
          databaseType: context?.databaseType ?? null,
          prefix,
          schema: context?.schema ?? null,
          suffix
        })

        const raw = yield* ollama.generate({ model: selectedModel, prompt })

        return { completion: normalizeCompletion(raw, prefix) }
      },
      Effect.catchAll((error) =>
        // Not a defect and not a 500: the editor shows nothing and the user keeps
        // typing. The warning is here so a broken setup is still discoverable.
        Effect.logWarning(
          `Could not generate a suggestion: ${error.message}`
        ).pipe(Effect.as({ completion: null } as CompletionResponse))
      )
    )

    return { complete, status } as const
  })
}) {}
